safe: true


domain: dlp.io/curricula
author: Digital Literacy Project
email: info@digiliteracy.org
title: DLP curricula

markdown: rdiscount

exclude: ['Rakefile', 'README.md', 'config.rb']

baseurl: '/curricula'